import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { motion, AnimatePresence } from 'framer-motion';
import { Light as SyntaxHighlighter } from 'react-syntax-highlighter';
import jsx from 'react-syntax-highlighter/dist/esm/languages/hljs/javascript';
import css from 'react-syntax-highlighter/dist/esm/languages/hljs/css';
import { atomOneDark } from 'react-syntax-highlighter/dist/esm/styles/hljs';
import {
  ArrowLeft, Code2, Loader2, Copy, Check, Download,
  RefreshCw, AlertCircle, Eye, EyeOff
} from 'lucide-react';
import { useAnalysis } from '../contexts/AnalysisContext';
import { codeGenApi } from '../services/api';

SyntaxHighlighter.registerLanguage('javascript', jsx);
SyntaxHighlighter.registerLanguage('css', css);

const DEFAULT_DEMO_CODE = {
  jsx: `import React, { useState } from 'react';
import styles from './Component.module.css';

/**
 * Redesigned Component
 * Generated by UI/UX Critic & Redesign Studio
 * 
 * Improvements applied:
 * - Clear visual hierarchy with proper type scale
 * - Accessible focus styles on all interactive elements
 * - 8px spacing grid system
 * - WCAG AA contrast compliance
 */
export default function RedesignedComponent({ title, description, onAction }) {
  const [focused, setFocused] = useState(false);
  
  return (
    <div className={styles.container}>
      <header className={styles.header}>
        <h1 className={styles.title}>{title}</h1>
        <p className={styles.description}>{description}</p>
      </header>
      
      <main className={styles.content}>
        <button
          className={styles.primaryCta}
          onClick={onAction}
          onFocus={() => setFocused(true)}
          onBlur={() => setFocused(false)}
          aria-label="Primary action"
        >
          Get Started
        </button>
        
        <a href="#learn-more" className={styles.secondaryLink}>
          Learn more →
        </a>
      </main>
    </div>
  );
}`,
  css: `/* Component.module.css
 * Generated by UI/UX Critic & Redesign Studio
 * Using 8px spacing grid, WCAG AA colors
 */

.container {
  display: flex;
  flex-direction: column;
  gap: 32px;
  padding: 48px;
  background: #0f172a;
  border-radius: 16px;
  border: 1px solid rgba(255, 255, 255, 0.08);
  max-width: 680px;
  margin: 0 auto;
}

.header {
  display: flex;
  flex-direction: column;
  gap: 12px;
}

.title {
  font-size: 2.25rem;
  font-weight: 800;
  color: #f1f5f9;
  letter-spacing: -0.02em;
  line-height: 1.2;
}

.description {
  font-size: 1rem;
  color: #94a3b8;
  line-height: 1.7;
  max-width: 480px;
}

.content {
  display: flex;
  align-items: center;
  gap: 24px;
  flex-wrap: wrap;
}

.primaryCta {
  padding: 14px 28px;
  background: #7c3aed;
  color: #fff;
  border: none;
  border-radius: 10px;
  font-size: 1rem;
  font-weight: 600;
  cursor: pointer;
  transition: all 200ms ease;
  outline: none;
}

.primaryCta:hover {
  background: #6d28d9;
  transform: translateY(-1px);
  box-shadow: 0 8px 24px rgba(124, 58, 237, 0.4);
}

/* Visible focus indicator - WCAG 2.1 requirement */
.primaryCta:focus-visible {
  outline: 3px solid #7c3aed;
  outline-offset: 3px;
}

.secondaryLink {
  color: #94a3b8;
  font-size: 0.9375rem;
  font-weight: 500;
  text-decoration: none;
  transition: color 150ms;
}

.secondaryLink:hover {
  color: #f1f5f9;
}`,
};

export default function CodeGeneratorPage() {
  const navigate = useNavigate();
  const { currentAnalysis, generatedCode, setGeneratedCode } = useAnalysis();
  const [activeTab, setActiveTab] = useState('jsx');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const [copied, setCopied] = useState(false);
  const [showPreview, setShowPreview] = useState(true);
  const [instruction, setInstruction] = useState('');

  const code = generatedCode || DEFAULT_DEMO_CODE;

  const handleGenerate = async () => {
    setError(null);
    setLoading(true);
    try {
      const result = await codeGenApi.generateCode({
        analysisData: currentAnalysis || {},
        userInstruction: instruction,
      });
      setGeneratedCode(result.code || result);
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  const handleCopy = async () => {
    const content = activeTab === 'jsx' ? code.jsx : code.css;
    await navigator.clipboard.writeText(content || '');
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const content = activeTab === 'jsx' ? code.jsx : code.css;
    const ext = activeTab === 'jsx' ? 'jsx' : 'css';
    const blob = new Blob([content || ''], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `RedesignedComponent.${ext}`;
    a.click();
    URL.revokeObjectURL(url);
  };

  // Build sandboxed HTML for preview
  const buildPreviewHtml = () => {
    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Preview</title>
  <style>
    body { margin: 0; padding: 24px; background: #0f172a; font-family: Inter, system-ui, sans-serif; }
    * { box-sizing: border-box; }
    ${code.css || ''}
  </style>
</head>
<body>
  <div style="color: #94a3b8; font-size: 0.875rem; margin-bottom: 16px; padding: 8px 12px; background: rgba(255,255,255,0.04); border-radius: 8px; border: 1px solid rgba(255,255,255,0.08);">
    ⚡ CSS Preview (isolated) · JSX requires a build environment
  </div>
  <div class="container">
    <header class="header">
      <h1 class="title">Redesigned Interface</h1>
      <p class="description">This component demonstrates the AI-applied improvements from the UX analysis.</p>
    </header>
    <main class="content">
      <button class="primaryCta">Get Started</button>
      <a href="#" class="secondaryLink">Learn more →</a>
    </main>
  </div>
</body>
</html>`;
  };

  return (
    <div style={{ minHeight: '100vh', display: 'flex', flexDirection: 'column' }}>
      {/* Header */}
      <div style={{
        position: 'sticky', top: 0, zIndex: 40,
        background: 'rgba(8,10,15,0.9)', backdropFilter: 'blur(12px)',
        borderBottom: '1px solid var(--border-subtle)',
        padding: '14px 32px',
        display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 12,
        flexWrap: 'wrap',
      }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
          <button className="btn btn-ghost btn-sm" onClick={() => navigate('/analysis-result')}>
            <ArrowLeft size={15} /> Back
          </button>
          <h2 style={{ fontSize: '1rem', margin: 0 }}>Code Generator</h2>
        </div>
        <div style={{ display: 'flex', gap: 10 }}>
          <button
            className="btn btn-secondary btn-sm"
            onClick={() => setShowPreview(!showPreview)}
            id="toggle-preview-btn"
          >
            {showPreview ? <EyeOff size={14} /> : <Eye size={14} />}
            {showPreview ? 'Hide Preview' : 'Show Preview'}
          </button>
          <button
            className="btn btn-primary btn-sm"
            onClick={handleGenerate}
            disabled={loading}
            id="generate-code-btn"
          >
            {loading ? <Loader2 size={14} className="animate-spin" /> : <Code2 size={14} />}
            {loading ? 'Generating...' : 'Generate with AI'}
          </button>
        </div>
      </div>

      <div style={{ flex: 1, padding: 32, display: 'flex', flexDirection: 'column', gap: 20 }}>
        {/* Custom instruction */}
        <motion.div
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          className="card"
          style={{ padding: 20 }}
        >
          <div style={{ display: 'flex', gap: 12, alignItems: 'flex-end' }}>
            <div style={{ flex: 1 }}>
              <label style={{ fontSize: '0.875rem', fontWeight: 600, color: 'var(--text-secondary)', display: 'block', marginBottom: 8 }}>
                Code Generation Instructions
              </label>
              <input
                type="text"
                className="input"
                placeholder="e.g., Use TypeScript, add form validation, include dark mode toggle..."
                value={instruction}
                onChange={(e) => setInstruction(e.target.value)}
                id="code-instruction-input"
              />
            </div>
            <button
              className="btn btn-primary"
              onClick={handleGenerate}
              disabled={loading}
              style={{ flexShrink: 0 }}
            >
              {loading ? <Loader2 size={16} className="animate-spin" /> : <RefreshCw size={16} />}
              {loading ? 'Generating...' : 'Generate'}
            </button>
          </div>
          {error && (
            <div className="alert alert-error" style={{ marginTop: 12 }}>
              <AlertCircle size={15} style={{ flexShrink: 0 }} />
              <span>{error}</span>
            </div>
          )}
          {!currentAnalysis && (
            <div className="alert alert-info" style={{ marginTop: 12 }}>
              <AlertCircle size={15} style={{ flexShrink: 0 }} />
              <span>Showing demo code. Run an analysis first to generate component code based on your specific design.</span>
            </div>
          )}
        </motion.div>

        {/* Code + Preview grid */}
        <div style={{
          display: 'grid',
          gridTemplateColumns: showPreview ? '1fr 1fr' : '1fr',
          gap: 20,
          flex: 1,
        }}>
          {/* Code panel */}
          <motion.div layout className="code-block" style={{ overflow: 'hidden' }}>
            <div className="code-header">
              <div className="tabs" style={{ border: 'none', background: 'transparent', padding: 0 }}>
                {['jsx', 'css'].map((tab) => (
                  <button
                    key={tab}
                    className={`tab-btn ${activeTab === tab ? 'active' : ''}`}
                    onClick={() => setActiveTab(tab)}
                    id={`tab-${tab}`}
                    style={{ padding: '5px 12px', fontSize: '0.8rem' }}
                  >
                    {tab.toUpperCase()}
                  </button>
                ))}
              </div>
              <div style={{ display: 'flex', gap: 6 }}>
                <button className="btn btn-ghost btn-sm" onClick={handleCopy} id="copy-btn">
                  {copied ? <Check size={13} color="var(--severity-low)" /> : <Copy size={13} />}
                  {copied ? 'Copied!' : 'Copy'}
                </button>
                <button className="btn btn-ghost btn-sm" onClick={handleDownload} id="download-btn">
                  <Download size={13} /> Download
                </button>
              </div>
            </div>
            <div className="code-content" style={{ padding: 0 }}>
              <SyntaxHighlighter
                language={activeTab === 'jsx' ? 'javascript' : 'css'}
                style={atomOneDark}
                customStyle={{
                  margin: 0,
                  padding: '20px',
                  background: 'transparent',
                  fontSize: '0.8125rem',
                  lineHeight: 1.7,
                  maxHeight: 600,
                }}
                showLineNumbers
              >
                {(activeTab === 'jsx' ? code.jsx : code.css) || '// Code will appear here after generation'}
              </SyntaxHighlighter>
            </div>
          </motion.div>

          {/* Preview panel */}
          <AnimatePresence>
            {showPreview && (
              <motion.div
                initial={{ opacity: 0, x: 20 }}
                animate={{ opacity: 1, x: 0 }}
                exit={{ opacity: 0, x: 20 }}
                className="card"
                style={{ overflow: 'hidden', display: 'flex', flexDirection: 'column' }}
              >
                <div style={{
                  padding: '12px 16px',
                  borderBottom: '1px solid var(--border-subtle)',
                  display: 'flex', alignItems: 'center', gap: 8,
                }}>
                  <Eye size={14} color="var(--text-muted)" />
                  <span style={{ fontSize: '0.875rem', fontWeight: 600, color: 'var(--text-secondary)' }}>
                    CSS Preview
                  </span>
                  <span className="badge badge-accent" style={{ fontSize: '0.65rem' }}>Sandboxed</span>
                </div>
                <iframe
                  title="Component Preview"
                  srcDoc={buildPreviewHtml()}
                  className="preview-iframe"
                  sandbox="allow-scripts"
                  style={{ flex: 1, border: 'none', height: '100%', minHeight: 500 }}
                />
              </motion.div>
            )}
          </AnimatePresence>
        </div>
      </div>
    </div>
  );
}
